title: Tunless Modern
description: Привычный доступ к любимым приложениям
theme: jekyll-theme-minimal
url: "https://michael-k-cloud.github.io/Tunless_Modern"
baseurl: "/Tunless_Modern"

# Navigation
nav_links:
  - title: Главная
    url: /Tunless_Modern/
  - title: Инструкция
    url: /Tunless_Modern/setup.html
  - title: Каринг
    url: /Tunless_Modern/karing.html
  - title: Соглашение
    url: /Tunless_Modern/terms.html
  - title: Конфиденциальность
    url: /Tunless_Modern/privacy.html
